version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap" -Dorg.gradle.daemon=false' 
    steps:
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - checkout
      - run:
          name: Download Dependencies 
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Run Tests
          command: ./gradlew check --no-daemon
          
  release_artifacts:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - run:
          name: Set signing key
          command: config/ci/download_keystore.sh
      - run:
          name: Set play store config
          command: config/ci/download_play_config.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Build and deploy
          command: ./gradlew assembleRelease --no-daemon
      - store_artifacts:
          path: tv/build/outputs/apk/release/
          destination: apk/tv
      - store_artifacts:
          path: mobile/build/outputs/apk/release/
          destination: apk/mobile

  play_store_internal:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - run:
          name: Set signing key
          command: config/ci/download_keystore.sh
      - run:
          name: Set play store config
          command: config/ci/download_play_config.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Build and deploy
          command: ./gradlew playUploadInternal --no-daemon
      - store_artifacts:
          path: tv/build/outputs/apk/release/
          destination: apk/tv
      - store_artifacts:
          path: mobile/build/outputs/apk/release/
          destination: apk/mobile

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - release_artifacts:
          requires:
            - build
          filters:
            branches:
              only:
                - release
      - play_store_internal:
          requires:
            - build
          filters:
            branches:
              only:
                - master

